### ISSUE TITLE
Common universal core

### ISSUE THREAD

**Issue by nikolay-govorov** [logux/core#21]
One of the main problems associated with the use of Logux, which I encounter in the need to raise the server on NodeJS. Often, especially on old projects, you want to use the server in an existing backend, for example as a separate microservice.

It would be very cool to have **a common language-independent core**. Such a kernel could be reused on the server as a native module and on the client as a WASM binding.

The [Rust](https://www.rust-lang.org) programming language can help with this. [Cargo](https://github.com/rust-lang/cargo) (official package manager and builder) supports compile build of the same package in both WASM and native FFI-bindings for any server language (including NodeJS/Python/C/C++/Ruby).

In addition, WASM allows you to use multithreading in the browser (already in Chrome)!

If we convert the kernel to Rust, we will get:

1. Common platform-independent kernel
2. Substantial increase in speed
3. Reducing weight klientka bindingof
4. Multithreading in the browser and on the server
5. The ability to create a cheap strapping for any popular platform

**Comment by ai** [comment]
First, lets me destroy your too optimistic way to look at Rust

> Common platform-independent kernel

Rust version is not language independent core. It is Rust version. You will not be able to run it in Ruby on Rails or PHP. You will still need a separated thread, which will communicate with Ruby and PHP by HTTP.

> Substantial increase in speed

Tell it `node-sass` ;). They are written in C++ and still 2 times slower than PostCSS written on JS. Architecture is important, no language.

> Reducing weight klientka bindingof

It is a good question of WASM final size. We could find a Rust dependencies, which are much bigger than JS, because was not optimized to client limits.

> Multithreading in the browser and on the server

Current core is very fast. Maybe Logux Redux could have benefited from it in time travel. But it definitely outside the idea of the core.

**Comment by ai** [comment]
Now, let’s me show how you should sell Rust:

1. We will need Logux for Android/iOS. We can’t run JS version there easily. Rust binaries will be much simpler to use in mobile native development.
2. Writing core on Rust could help in promotion because Rust community will look into Logux. Also, many web developers will think that it is fast because they have the wrong idea about performance in their heads :).

**Comment by ai** [comment]
Yeap, I agree that rewriting it to Rust could be a cool idea.

Here is the current plan:

1. Finish some new secret project.
2. Write docs.
3. Write WYSIWYG solution.
4. Only then I will have time to rewrite it to Rust. 

This plan is good also because at that moment IE will be finally dead, so we will be free to use WASM.

**Comment by nikolay-govorov** [comment]
Thanks for answer

> You will still need a separated thread, which will communicate with Ruby and PHP by HTTP.

It's not. We are talking about using the core as a [FFI](https://en.wikipedia.org/wiki/Foreign_function_interface) library inside PHP/Python. This is not a separate application or a separate thread – just an extension

> Architecture is important, no language

> Reducing weight klientka bindingof

Of course, architecture is a critical factor, but other things being equal, binary format is less than text, and WASM is faster than browser JS.

**Comment by nikolay-govorov** [comment]
> at that moment IE will be finally dead

WASM can be perfectly polifill (via asm.js) and under IE :)

**Comment by ai** [comment]
> It's not. We are talking about using the core as a FFI library inside PHP/Python. This is not a separate application or a separate thread – just an extension

So how you will fix the concurrency problem of Ruby/PHP with FFI?

They anyway will freeze thread when you pass anything to FFI. So you will be forced to run a thread for every web socket user. It will kill performance on 100 users (again, a good reminder that architecture for performance is not more important that language).

> binary format is less than text

minification + gzip does pretty similar work that compiling to bytecode.

In another hand, one big dependency from Rust could kill all benefits from delivering bytecode.

(there is a one really good benefit of delivering bytecode than JS. You do not need to parse and compile bytecode, so it will be run faster. But I am not sure, did they implement it already).

> WASM is faster than browser JS

Again, node-sass is written on C++, which is even faster than WASM, but still slower than PostCSS.

Math operation performance should not be considered as performance (until you do not do something math-specific like codecs). 

> WASM can be perfectly polifill (via asm.js) and under IE :)

Can you have just “out of the box” solution for this polyfill? What users will do to use it?

**Comment by nikolay-govorov** [comment]
> Can you have just “out of the box” solution for this polyfill? What users will do to use it?

Nothing. We'll just put them down `.js` file (in `asm.js`), instead `.wasm` file. This build-level solution has no impact on the user

> Math operation performance should not be considered as performance

WASM allows you to work with memory (and manage it effectively, with the right architecture). It, as you correctly noted, does not require JIT compilation parsing and speculative optimizations. It is faster not only in mathematical operations, any operation in WASM is faster because of the simplification of the task for the engine

> In another hand, one big dependency from Rust could kill all benefits from delivering bytecode.

A great reason to make a size-limit for Rust, isn't it?)

> freeze thread when you pass anything to FFI

I suggest porting only the core. The kernel wrapper for `logux-server` can solve the synchronization problem specifically and effectively for the receiving language, such as event-loop for NodeJS and Python (`async` package)

**Comment by ai** [comment]
> Nothing. We'll just put them down .js file (in asm.js), instead .wasm file. This build-level solution has no impact on the user

But how webpack will automatically server `.js` files to IE users?

> A great reason to make a size-limit for Rust, isn't it?)

I like the idea :D. Do you want to write it?

> The kernel wrapper for logux-server can solve the synchronization problem specifically

The solution for PHP/Ruby will be the same as for Node.js. Run separated server and communicate by HTTP with Ruby/PHP server.

BTW, how do you plan to write web socket server on Rust? What is the current recommendation for concurrency? (event loop is not the best option since it uses only one CPU core)

**Comment by ai** [comment]
Seems like Tokio is our choice in terms of concurrency since it provides ”green threads”.

One more note. There is no sense to rewrite only core since it is just set of helper functions. The real magic happens in `logux-server` and API-specific parts (like Web Sockets reconnection system).

I like the idea of Rust’s Logux and I will start it. But a little later, because the core is small and rewriting it to Rust will not help us. But rewrite the whole system is a good idea.

Here is a question that we need to solve before rewriting:

1. How exactly we will connect it with Web Sockets in a browser, We also need to have a solution for ServiceWorker `sync` event. And maybe even deliver new data by push.
2. How we will connect it with iOS/Android app. The main problem here is that we can’t keep WS connection. We need to use only push to get new actions.
3. When we will rewrite the whole server on Rust (I especially like this idea) can we allow a user to define some callbacks on Node.js? It is optional, we can always ask users to execute separated HTTP server.

**Comment by nikolay-govorov** [comment]
> But how webpack will automatically server .js files to IE users?

It won't be a `Webpack`, it'll be a `Cargo`. 2 compilation targets will be configured: in `WASM` and in `asm.js`. The output will be 3 files in the `build.wasm` (the binary itself), `build.js` (a thin wrapper for the use of WASM in JS), `build.asm.js` (slow build for older browsers).

> Do you want to write it?

It seems to be harder than JS. I could take up this, if the development will be carried out for a specific task.

> The solution for PHP/Ruby will be the same as for Node.js. Run separated server and communicate by HTTP with Ruby/PHP server.

The only difference is that you don't need to install Node. I suggest using the kernel on Rust not as a standalone application, but as a FI module that is used directly from Python/PHP/NodeJS. This is similar to the API for Node JS, with the difference that FI is a generic Protocol and the N-API is built for Node.

> BTW, how do you plan to write web socket server on Rust

When I came up with this issue, I wasn't planning on writing the server in Rust, but I like the idea. For Rust, there's the Tokio – asynchronous green-thread runtime you mentioned.

I like the idea of implementing a full platform-independent server on Rust. We can implement an RPC interface and build a wrapper for any language like Node/Python/PHP. We can even ship the entire linux server as a package that you just need to install from NPM/PIP/Packager.

**Comment by nikolay-govorov** [comment]
> Here is a question that we need to solve before rewriting

1. As in NodeJS. Rust can do great in WebSockets. [For example](https://github.com/websockets-rs/rust-websocket/tree/master/examples)

2. It's more complicated and language independent. We need to understand how we can send push to the client. I don't know how it can work yet (maybe push notifications?), but I'm sure there is a solution. On the other hand, running binaries on mobile devices is much easier than JS.

3. Certainly. We can provide the CGI API out, I for languages like Python/Node to supply thin wrapper clients to work with this API. I really like the idea of learning how to package `logux-server` into a NodeJS/PHP/Python/Ruby package and putting **all `logux-server`** from NPM/PIP so that all logux-server management is from user code (`npm i logux-server` looks very simple and transparent, doesn't it?)

**Comment by nikolay-govorov** [comment]
In general, I thought that we can keep a connection to the server when the application is running, and send only native push notifications in the background.

When it comes to mobile applications, I think that we can only communicate with the running application (at least in the background). What prevents the application from starting to raise the connection and get the state?

**Comment by nikolay-govorov** [comment]
> How they will add Logux Client to the project with IE support

A lot of options. The easiest to write `const LoguxClient = require('login-client')`, and the client to dynamically select the right module to use. You can also offer Lotus client without polyphile, `const LoguxClient = require ('login-client/wasm')`

> PHP doesn’t support the right concurrency model to be used with Web Sockets

LoguxServer course itself should work with sockets. But how does this prevent us from delivering it as a module for the language? We run the Python server send Python logs but with the network working on their own. I'm not suggesting (already) put the blame on the user of network issues, but I really want to LoguxServer not it was necessary to put separately. This greatly complicates the infrastructure.

> You can’t keep the application in the background in iOS. Same in Service Worker.

And how now does Service Worker get a push?

**Comment by nikolay-govorov** [comment]
> It will increase bundle size.

NPM package, but not the final bundle. In the Assembly, the user will receive only what is needed (asynchronously load the polyphyl, if necessary)

> It doesn’t

It seems to me that it's not rust, but the architecture itself. It is not clear how this should work at all.

> I am not sure that it possible in FI.

I think it should work fine. We run a linux server from FFI, and then the server on rust raises the connection with clients

**Comment by ai** [comment]
> NPM package, but not the final bundle. In the Assembly, the user will receive only what is needed (asynchronously load the polyphyl, if necessary)

Async loading can be done just by `require('logux-client')`. For async loading user will need to define new bundle.

> It seems to me that it's not rust, but the architecture itself.

Yeap

> e run a linux server from FFI, and then the server on rust raises the connection with clients

What concurrency model does it provide?

As I know FFI, runs in the same thread of app (at least what I saw in Ruby and Node.js)

**Comment by nikolay-govorov** [comment]
Can you read more as you see the new server on Rust? When I started this discussion, everything was simple and clear – a common module with utilities that compiles to wasm and FFI.

The first thing to understand-not everything that can work on the server will also work in WASM. A great example is WebSockets. WASM is working in a sandbox, and queries will in any case make JS. Another thing is that we can effectively work with the log in WASM, where necessary to get this log in JS. I'm not sure that this architecture is worth the candle.

Things are very different with `logux-server` – things get more complicated (although I love the idea), but we can get a platform independent zero-dependencies server.

The key question is in what language does the user write logic? The whole architecture depends on it.

I'm assuming that business logic should be written in the receiving language, be it Node/Python or Ruby. Otherwise, DX approaches zero, and the learning curve grows prohibitively.

The second question is, will 'logux-server' be a separate module providing an RPC interface and installed directly by the user, or will it be part of a language-specific package (like `node-sqlite3`)?

On the one hand, if `logux-server` is an independent server, it is much more flexible to configure the architecture (it seems that it is not necessary to have a logux-server instance for each NodeJS server instance), and for example, to have separate servers where only `logux-server`will be. This is also cool because we can use any architecture for multithreading.

On the other hand, we can supply `logux-server` as part of the npm/pip package. This greatly simplifies the user's life, because he does not need to put a separate product, as it is now with NodeJS. This is actually the only advantage, but it is very important. The problem with this approach is that there are problems with multithreading specific to the receiving language (for example, there are people programming in PHP).

**Comment by nikolay-govorov** [comment]
Ideally, I want to see both options, so that the wrapper on the rpc that we use in the host language during development worked as a single package, and in the product could work with a separate server (RPC or HTTP)

**Comment by ai** [comment]
> The key question is in what language does the user write logic? The whole architecture depends on it.

My current view is that it is better to push user logic away from Logux Server. Anyway, users will want PHP and Ruby. So it is better to run Logux Server as a separated server and just communicate with PHP/Ruby backend by HTTP.

> On the other hand, we can supply logux-server as part of the npm/pip package.

We can keep Logux Server and separated server, but just put binary to npm package (**without FFI**, since it can do concurrency).

**Comment by nikolay-govorov** [comment]
Good plan. The only thing is, since we still won't force the user to go to bare http, I would suggest using not http, but RPC, as a more suitable and effective tool

**Comment by nikolay-govorov** [comment]
It turns out that technically it is not clear only how to handle IE? It seems to me, before solving this problem, it is necessary to understand whether the game with wasm spent forces

**Comment by ai** [comment]
> I would suggest using not http, but RPC

What exactly protocol do you recommend? (since RPF is just an idea, there are many HTTP based RPC protocols as well).

Right now unreleased Logux 3 uses custom JSON format + HTTP for RPC.

We also thought about gRPC (HTTP 2 + Protocol Buffers), but found problems with typing (since action has open structure).

**Comment by nikolay-govorov** [comment]
I went deep into the theory, and it seems that `gRPC` is the best option. Moreover, it [can be used in Rust](https://github.com/stepancheg/grpc-rust)

**Comment by ai** [comment]
@ nikolay-govorov I think HTTP+JSON and gRPC will be the best like combination.

Keeping HTTP will be useful, since it very simple.

How l do you think we can solve the problem of open structure in actions and gRPC typing.

**Comment by nikolay-govorov** [comment]
Maybe. Can you tell me more about the problem? What prevents to describe the types of action, and user input to serialize a string?

**Comment by nikolay-govorov** [comment]
In any event, it is serializable technical information about action. Theoretically, we can allow the user to describe the meta structure

**Comment by ai** [comment]
> but definitely save traffic

Are you sure? The whole command is just `action` and `meta`

**Comment by nikolay-govorov** [comment]
It seems that a large number of requests, even typing action will save traffic, but in General we need benchmarks

**Comment by nikolay-govorov** [comment]
Especially since even if we can't make better use of Protobuf, we still get benefits from gRPC

**Comment by ai** [comment]
I am closing it since for few next years we will keep a JS core
